#!/bin/bash

echo "=== AIXien Platform 504 Timeout Fix Deployment Script ==="
echo ""
echo "This script will help fix the 504 timeout errors on your EC2 server."
echo ""

echo "Please run these commands on your EC2 server:"
echo ""
echo "1. First, update nginx configuration:"
echo "   sudo cp /home/ubuntu/aixien-platform/nginx.conf /etc/nginx/sites-available/aixien.com"
echo "   sudo nginx -t"
echo "   sudo systemctl reload nginx"
echo ""
echo "2. Then, restart the application with PM2:"
echo "   cd /home/ubuntu/aixien-platform"
echo "   git pull"
echo "   npm install"
echo "   npm run build"
echo "   pm2 delete aixien-platform"
echo "   pm2 start ecosystem.config.js"
echo "   pm2 save"
echo "   pm2 startup"
echo ""
echo "3. Monitor the logs:"
echo "   pm2 logs aixien-platform"
echo ""
echo "4. If you're still getting 504 errors, check:"
echo "   - Server memory: free -h"
echo "   - PM2 status: pm2 status"
echo "   - Nginx error logs: sudo tail -f /var/log/nginx/error.log"
echo ""

echo "Additional optimization options if needed:"
echo ""
echo "Option A - Use smaller knowledge base (already implemented with 10s timeout)"
echo "Option B - Increase server resources (upgrade EC2 instance type)"
echo "Option C - Use Redis for caching GitHub content"
echo ""